In [1]:
import pandas
import datetime
import numpy
import scipy.optimize
import seaborn as sns
import matplotlib.pyplot as plt
import os
from matplotlib.colors import ListedColormap
from matplotlib.colors import Normalize
from matplotlib import ticker
%matplotlib inline

In [7]:
def convert_to_datetime(row):
    return datetime.datetime(2013, 6, 22, int(row["hour"]),\
                             int(row["minute"]), int(row["second"]) )

# Read the ExB drift and sc potential data
exbFile = "/Users/bharat/Documents/code/vap-analys/" +\
            "data/SAIS_SAPS_withdata/selected_SAPS/" +\
            "A_130622/SAPS_data_ExB_iono_A_2013062205000700.txt"
scPotFile = "/Users/bharat/Documents/code/vap-analys/" +\
            "data/SAIS_SAPS_withdata/selected_SAPS/" +\
            "A_130622/SAPS_data_SCPOT_A_2013062205000700.txt"
exbColNames = [ "dec_hour", "radial_vel", "azim_vel" ]
scPotColNames = [ "dec_hour", "sc_potential" ]
exbRbspDF = pandas.read_csv(exbFile, delim_whitespace=True,\
                            header=None, names=exbColNames)
scPotRbspDF = pandas.read_csv(scPotFile, delim_whitespace=True,\
                            header=None, names=scPotColNames)
# Add a datetime field from the dec_hour field
scPotRbspDF["hour"] = [ int(x) for x in scPotRbspDF["dec_hour"] ]
scPotRbspDF["minute"] = [ int( ( x - int(x) ) * 60. ) for x in scPotRbspDF["dec_hour"] ]
scPotRbspDF["second"] = [ ( x - int(x) ) for x in scPotRbspDF["dec_hour"] ]
scPotRbspDF["second"] = [ ( x * 60. )  for x in scPotRbspDF["second"] ]
scPotRbspDF["second"] = [ int( (x - int(x))*60 )  for x in scPotRbspDF["second"] ]
# The same for exb vels
exbRbspDF["hour"] = [ int(x) for x in exbRbspDF["dec_hour"] ]
exbRbspDF["minute"] = [ int( ( x - int(x) ) * 60. ) for x in exbRbspDF["dec_hour"] ]
exbRbspDF["second"] = [ ( x - int(x) ) for x in exbRbspDF["dec_hour"] ]
exbRbspDF["second"] = [ ( x * 60. )  for x in exbRbspDF["second"] ]
exbRbspDF["second"] = [ int( (x - int(x))*60 )  for x in exbRbspDF["second"] ]

# scPotRbspDF["date"] = [ datetime.datetime(2013,6,22,int(x)) for x in scPotRbspDF["dec_hour"] ]

scPotRbspDF["date"] = scPotRbspDF.apply( convert_to_datetime, axis=1 )
exbRbspDF["date"] = exbRbspDF.apply( convert_to_datetime, axis=1 )

exbRbspDF.head()

   dec_hour  radial_vel   azim_vel  hour  minute  second                date
0   5.00250   -141.4780   67.50610     5       0       9 2013-06-22 05:00:09
1   5.00558   -382.4320  353.50000     5       0      20 2013-06-22 05:00:20
2   5.00867    -55.7790  109.49900     5       0      31 2013-06-22 05:00:31
3   5.01175    257.0170   42.89340     5       0      42 2013-06-22 05:00:42
4   5.01483   -138.4950 -634.37500     5       0      53 2013-06-22 05:00:53
5   5.01792   -296.7890 -616.37800     5       1       4 2013-06-22 05:01:04
6   5.02100   -255.8740 -306.89600     5       1      15 2013-06-22 05:01:15
7   5.02408    -19.6576   -2.70319     5       1      26 2013-06-22 05:01:26
8   5.02717    -76.3784  708.96600     5       1      37 2013-06-22 05:01:37
9   5.03022   -312.2680  789.59400     5       1      48 2013-06-22 05:01:48